name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: cargo fmt --check --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lint
      run: cargo clippy --verbose -- --deny warnings

  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: TDD check new tests against old binary
      run: |
        case '${{ github.event.pull_request.title }}' in
          fix*|feat*|bug*)
            git fetch --all
            git reset --hard ${{ github.event.pull_request.base.sha }}
            cargo build --release
            git checkout ${{ github.sha }} -- tests
            !cargo test --verbose
            ;;
        esac
